[project]
name = "emailbreach-check"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "termcolor>=3.2.0",
    "requests"
]
